### ISSUE TITLE
Schema might be inappropriate, better to use profile

### ISSUE THREAD

**Issue by larsgsvensson** [ProfileNegotiation/I-D-Accept--Schema#1]
From email conversation on DC-Architecture (comments by Antoine and myself where Antoine suggests to use "profile" instead):

> > ...] I have read the doc about 'profiles' in HTTP, and I agree with you. It's actually
> > quite hard to tell whether it covers our profiles or it's something completely
> > different. I feel a bit reluctant about discarding it, though, because
> > https://tools.ietf.org/html/rfc6906 mentions DC as one case (even though
> > the old DC-HTML that RDF6906 uses may not be one of the profiles our group
> > have in mind)
> 
> My reading is that RFC 6906 profiles are a different kind of beast than a DC AP. From what I understand, this kind of profile is more like a restriction on an existing format, so that DC-HTML would be a subset of HTML (probably of HTML 4.X) saying what html elements could be used. One _could_ argument, that a DC AP is a subset of all possible metadata elements but that seems too much of a stretch.
> 
> > Is it used a lot? If not, then maybe you could just do a bit of landgrabbing and
> > claim it yours (after adding some precisions to the original definition).
> 
> I don't know how much it's used, but I'm very reluctant to re-use a term with different semantics...

Maybe this would be worth flagging this to Arnaud when you send it? I completely understand your reluctance, but if the HTTP 'profiles' are not used and their semantic is vague, then the ID could be about adapting them to your goals. To me it's better to re-visit an unused feature to match a promising goal rather than creating a new one, which could make users very puzzled. The fact that 'profile' has unclear semantics and usage would always bring nuisance for the adoption of your solution.

**Comment by larsgsvensson** [comment]
Comment from Karen (also on DC-Architecture):

> My suggestion to call it "schema" goes back to my conversation with Arnaud last year where he told me that if "RDF Schema" hadn't been taken already, the RDF Data Shapes probably would have been named RDF Schema analogous to XML Schema. And since the content negotiation should not only be on RDF Shapes but on any kind of restricting schema (or AP), e. g. an XML schema or a DC AP, I decided to call the header Accept-schema. I'll keep that for the time being and add some comments to the I-D on the naming when I send it to Arnaud.

Just as an FYI, there has been discussion in the W3C group that SHACL is 
analogous to XML schema. I see a bit of a difference, because XML and 
RDF are so different, and XML schema does what RDF Schema + SHACL would 
achieve (definition of terms and constraints, which are done together in 
XML schema).

Since Lars is talking about making a choice that could be between RDFS 
and XML/S and JSON and more, then the generic term "schema" makes sense 
to me -- and I can't think of another that would make sense.

**Comment by larsgsvensson** [comment]
Discussion at SDSVoc clarified that "profile" would be the most appropriate term, so I've changed this everywhere.

**Comment by RubenVerborgh** [comment]
See #14.

**Comment by larsgsvensson** [comment]
Until we know if the things we want to negotiatiate are profiles (as in RFC 6906) or schemas, we cannot decide on the naming. Cf #11
