### ISSUE TITLE
Terminology: media type or MIME type?

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Accept--Schema#10]
I prefer "media type", but MIME is an RFC. Would be good to express the equivalence of both terms anyway.

**Comment by larsgsvensson** [comment]
I prefer "media type", too.

**Comment by hvdsomp** [comment]
media type is commonly used in RFCs

H

**Comment by larsgsvensson** [comment]
OK, then we'll use that. I shall update the text.
