### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Accept--Schema#14]
We should probably change "I-D-Accept--Schema" into something more accurate.

**Comment by larsgsvensson** [comment]
WFM as long as we ping @philarcher1 so that he can update the W3C documentation...

**Comment by philarcher1** [comment]
I am pinged.

But may not get to update the W3C docs today

On 24/04/2017 11:13, Lars G. Svensson wrote:
> WFM as long as we ping @philarcher1 so that he can update the W3C documentation...
>

-- 


Phil Archer
Data Strategist, W3C
http://www.w3.org/

http://philarcher.org
+44 (0)7887 767755
@philarcher1

**Comment by RubenVerborgh** [comment]
Okay, let's maybe do this final rename today then, before @philarcher1 updates.

**Comment by RubenVerborgh** [comment]
Proposal: https://github.com/ProfileNegotiation/Internet-Draft/ (vote on this message or create another)

**Comment by larsgsvensson** [comment]
The repository name will still be "ProfileNegotiation" though, so we're stuck with "profile" even if we rename to "schema"

**Comment by RubenVerborgh** [comment]
Even that could change if needed.

**Comment by larsgsvensson** [comment]
The re-write of the document is now in https://github.com/ProfileNegotiation/I-D-Profile-Negotiation
