### ISSUE TITLE
TXT or XML version?

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Accept--Schema#6]
The repository currently consists of two versions; it might be hard to keep those in sync during drafting.
Can one document somehow be derived from the other?

**Comment by RubenVerborgh** [comment]
I will start working on the XML version, as this is the richest representation of the two.

**Comment by larsgsvensson** [comment]
Yes, the XML version is the canonical one. We can use that to derive the TXT version e. g. by using [xml2rfc](https://xml2rfc.tools.ietf.org/)

**Comment by RubenVerborgh** [comment]
I'd propose to remove the TXT version from the repository then; I can set up continuous integration so it is autogenerated in a separate branch upon every commit.

**Comment by larsgsvensson** [comment]
> I'd propose to remove the TXT version from the repository then

Done

> I can set up continuous integration so it is autogenerated in a separate branch upon every commit.

Yes please!

**Comment by RubenVerborgh** [comment]
Alright, can you give me admin access to the repo so I can set this up?

**Comment by larsgsvensson** [comment]
Just to show how little I know about GitHub: How do I do that? (I looked under settings/collaborators but couldn't find anything...)

**Comment by RubenVerborgh** [comment]
settings/collaboration, and then under the "Collaborators" section at the bottom, give me "admin" access normally.

**Comment by larsgsvensson** [comment]
Sorry, don't have that. I can only add (or remove) collaborators but not give them any extra privileges. Perhaps it's a feature you have to pay for?

**Comment by RubenVerborgh** [comment]
I suppose it's a feature that only exists on organisations; that's where I was copying the steps from. Hmm… perhaps it makes sense to move this to a (mini-)organisation?

**Comment by larsgsvensson** [comment]
No objection from me! Can you set it up?

**Comment by RubenVerborgh** [comment]
Yes, please transfer this repository to the organisation `ProfileNegotiation`.

**Comment by hvdsomp** [comment]
And can we all please have write access so we don't need to fork all the time?

Cheers

H

**Comment by RubenVerborgh** [comment]
Write access already set up, now just waiting for transfer :-)

**Comment by larsgsvensson** [comment]
Done

**Comment by RubenVerborgh** [comment]
Build automatically to the gh-pages branch; text available at http://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema.txt

**Comment by RubenVerborgh** [comment]
…and HTML too: http://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema.html
