### ISSUE TITLE
Terminology: host and UA or client and server?

### ISSUE THREAD

**Issue by RubenVerborgh** [ProfileNegotiation/I-D-Accept--Schema#9]
I wonder whether the terms "client" and "server" would make the text easier to read.

It seems that "host" and "User Agent" (especially in its abbreviation "UA") unnecessarily complicate the text. Furthermore, many clients are strictly speaking not "User Agents" either.

**Comment by larsgsvensson** [comment]
I frankly don't know which is the best terminology to use for this but agree that "client" and "server" make the text easier to read.

**Comment by hvdsomp** [comment]
user agent and server are commonly used in RFCs.

H

**Comment by larsgsvensson** [comment]
OK, then we stick to that terminology. I'll update the text
